server:
    port: 8080
spring:
  application:
    name: "project-management-service"
  profiles:
    active: "dev"
## Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update #for testing purpose changing it to 'update' or 'validate' and has your schema created in your database
      show-sql: true
springdoc:
  swagger-ui:
    path : "/swagger-ui.html"
  api-docs:
    path : "/api-docs"