server:
    port: 8080
logging:
    level:
        org:
            springframework: DEBUG
            hibernate: DEBUG
spring:
  application:
    name: "project-management-service"
  profiles:
    active: "dev"
## Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # change this to your database name
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop #for testing purpose changing it to 'update' or 'validate' and has your schema created in your database
      show-sql: true
      format_sql: true
springdoc:
  swagger-ui:
    path : "/swagger-ui.html"
  api-docs:
    path : "/api-docs"