server:
    port: 8080
spring:
  application:
    name: "project-management-service"
  profiles:
    active: "dev"
springdoc:
  swagger-ui:
    path : "/swagger-ui.html"
  api-docs:
    path : "/api-docs"