name: Wake Render Server

on:
  schedule:
    # Runs every 5 minutes (adjust as needed to keep your server awake)
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows you to trigger manually if needed

jobs:
  wake-server:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to wake the server
        env:
          COMPANY_ID: ${{ secrets.COMPANY_ID }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
            curl -H "Authorization: Bearer $TOKEN" -X GET "https://fs19-pm-be-java.onrender.com/$COMPANY_ID/$WORKSPACE_ID" || echo "Failed to wake server"
